### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by PFCKrutonium** [IrcDotNet/IrcDotNet#21] opened 2016-03-06 06:56 UTC
![error](https://cloud.githubusercontent.com/assets/3945538/13552795/ad30a33e-e33e-11e5-9381-3486c103a47e.PNG)

Honestly I have no clue. Connecting to Twitch.

**Comment by PFCKrutonium** [comment] 2016-03-06 07:08
Source:

```
Imports IrcDotNet
Module Module1
    Dim WithEvents Client As New TwitchIrcClient
    Dim User As IrcUser

    Dim OAuth As String = "oauth password"
    Dim Username As String = "PFCKrutonium"

    Dim Server As String = "irc.twitch.tv"
    Sub Main()
        Console.WriteLine("Connecting to Twitch as " & Username)
        Client.FloodPreventer = New IrcStandardFloodPreventer(4, 2000)

        'Client.Connect(Server, False,
        '                    New IrcUserRegistrationInfo() {
        '                        NickName = Username,
        '                        Password = password,
        '                        Username = Username})
        Dim Info As New IrcUserRegistrationInfo
        Info.NickName = Username
        Info.Password = OAuth
        Info.UserName = Username

        Client.Connect(Server, False, Info)

        Console.ReadKey()
    End Sub

    Sub Connected(ByVal sender As Object, ByVal e As EventArgs) Handles Client.Connected
        Console.WriteLine("Connected")
    End Sub

    Sub Registered(ByVal sender As Object, ByVal e As EventArgs) Handles Client.Registered
        Console.WriteLine("Registered")
        Client = DirectCast(sender, IrcClient)

        'Client.LocalUser.NoticeReceived += IrcClient_LocalUser_NoticeReceived;
        '    Client.LocalUser.MessageReceived += IrcClient_LocalUser_MessageReceived;
        '    Client.LocalUser.JoinedChannel += IrcClient_LocalUser_JoinedChannel;
        '    Client.LocalUser.LeftChannel += IrcClient_LocalUser_LeftChannel;


    End Sub
    Sub ConnectFailed(ByVal sender As Object, ByVal e As EventArgs) Handles Client.ConnectFailed
        Console.WriteLine("Connection Failed")
        Console.ReadKey()
        Environment.Exit(1)
    End Sub

    Sub MessageRecieved(ByVal Sender As Object, ByVal e As IrcMessageEventArgs)

    End Sub

End Module
```

**Comment by chimera74** [comment] 2016-03-14 18:09
I have the same issue on my all new projects with this library. One old project has no issue with it and I can not figure out why. But I'm about to. I'll post what I'll find.

**Comment by parabola949** [comment] 2016-03-16 18:23
Same issue here.  I get my bot to reply, and I immediately get a very similar error.  @chimera74 mentioned an old project was working, so I downgraded the NuGet package to v0.5, and it's working again.  Appears to be a bug in 0.6.

**Comment by chimera74** [comment] 2016-03-16 19:29
I came to downgrading to v0.5 solution too. =(
Odd thing that old project is working with any version I download from NuGet even with the latest one notably. I also changed to latest version of framework (4.6.1) on that project (same as other projects). Could not make it not to work.
I am out of ideas what is causing this.
Using Windows 10, MSVS Community 2015 v14.0.24720.00 Update 1.

**Comment by paralin** [comment] 2016-04-17 21:39
Apologies for taking a while to get around to this.

Is there any way you can capture that error in text form (not a debug popup) so I can have a closer look? Can you send some code to replicate it, preferably in c#?

Thanks!

**Comment by paralin** [comment] 2016-04-17 22:34
I translated your code to C# and can't reproduce it.

**Comment by PFCKrutonium** [comment] 2016-04-18 04:22
I'm nowhere near a Windows PC at the moment, but if you make a Visual Basic Console Application, and copy/paste my code (and install the library), then you can direct the output whereever you want.

**Comment by paralin** [comment] 2016-04-19 18:11
@PFCKrutonium I tried it on my end without errors.

If you can reproduce please re-open. For now I'll assume it was fixed in the new version.

**Closed by paralin** 2016-04-19 18:11 UTC
Labels: bug
